import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Almarai,ABeeZee } from "next/font/google";
import "./globals.css";
import {Providers} from './providers';
import ThemeProvider from "@/context/Theme";
import { SessionProvider } from "next-auth/react";

import { auth } from  "../auth"; // 引用您在 auth.ts 中導出的 auth 函數，並重新命名以避免潛在衝突

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const almarai = Almarai({
  variable: "--font-almarai",
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
});
const abeezee = ABeeZee({
  variable: "--font-abeezee",
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "GOMORE Model Library",
  description: "Generated by create next app",
};

const RootLayout=async({children}: {children: React.ReactNode}) =>{
  const session = await auth(); // 獲取當前用戶的會話信息
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${almarai.variable} ${abeezee.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <ThemeProvider 
            attribute="class" 
            defaultTheme="dark"
            enableSystem={false}
            disableTransitionOnChange
          >
            {/*wrapped the children between ThemeProvider to make sure the theme aplly ot all pages*/}
              {/* hero ui provider */}
              <Providers>              
                  {children}
              </Providers>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}

export default RootLayout;


